compile:
	javac Tarea3/JavaHack.java Tarea3/Arma.java Tarea3/Enemigo.java Tarea3/Equipamiento.java Tarea3/Item.java Tarea3/Mundo.java Tarea3/Personaje.java Tarea3/Vacio.java Tarea3/Visible.java

run:
	java Tarea3/JavaHack

clean:
	rm Tarea3/*.class